### Get All Categories
GET http://localhost:3000/api/categories
Accept: application/json

### Create a Category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Computer"
}

### Get a Category by ID
GET http://localhost:3000/api/categories/2
Accept: application/json

### Update a Category
PUT http://localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json

{
  "name": "Fashion"
}

### Delete a Category
DELETE http://localhost:3000/api/categories/2
Accept: application/json